services:

  demo-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: demo-backend
    environment:
      ENVIRONMENT: dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo
      POSTGRES_SCHEMA: backend
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres:17.3-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo
    volumes:
      - psql-pv:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  psql-pv:
